name: Deploy GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: create dir for html output
        run: mkdir public
      - name: Buid Page
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: public/index.html
      - name: upload html site to pages artifact 
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
      - name: deploy pages
        uses: actions/deploy-pages@v1
